[project]
name = "ibm_ds"
version = "0.1.0"
description = ""
authors = [{ name = "eoamegassi", email = "eliseeamegassi@gmail.com" }]
requires-python = ">=3.13,<3.14"
readme = "README.md"
dependencies = [
    "requests>=2.34.2",
    "numpy>=2.0",
    "scikit-learn>=1.9.0",
    "beautifulsoup4>=4.15.0",
    "sqlalchemy>=2.0.51",
    "matplotlib>=3.11.1",
    "seaborn>=0.13.2",
    "wget>=3.2",
    "jupyterlab>=4.6.2",
    "jupyter>=1.1.1",
    "jupyterlab>=4.6.2",
    "ipython-sql>=0.5.0",
    "folium>=0.17.0",
    "dash>=2.18.2",
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.3.260113",
    "plotly>=6.9.0",
    "anywidget>=0.11.0",
    "statsmodels>=0.14.6",
    "scipy-stubs>=1.18.0.1",
    "phik>=0.12.5",
    "marimo[lsp,recommended,sql]>=0.23.16",
    "optuna>=4.9.0",
]

[tool.marimo.language_servers.pylsp]
enabled = true               # Enable/disable pylsp
enable_mypy = true           # Type checking with mypy (enabled by default, if installed)
enable_ruff = true           # Linting with ruff (enabled by default, if installed)
enable_flake8 = false        # Linting with flake8
enable_pydocstyle = false    # Check docstring style
enable_pylint = false        # Linting with pylint
enable_pyflakes = false      # Syntax checking with pyflakes
